// examples/react-mic-visualizer/src/app.tsx
import type { Segment } from '@saraudio/core';
import { meter } from '@saraudio/meter';
import { useAudioInputs, useRecorder } from '@saraudio/react';
import type { RuntimeMode } from '@saraudio/runtime-browser';
import { buildAudioConstraints, segmentToAudioBuffer } from '@saraudio/runtime-browser';
import { vadEnergy } from '@saraudio/vad-energy';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

const formatDuration = (ms: number): string => `${(ms / 1000).toFixed(2)} s`;

const formatTimestamp = (ms: number): string => `${(ms / 1000).toFixed(2)} s`;

const VADMeter = ({ score, speech }: { score: number; speech: boolean }) => {
  const percentage = Math.min(100, Math.max(0, Math.round(score * 100)));
  return (
    <div className='vad-meter'>
      <div className='vad-meter__bar' style={{ width: `${percentage}%` }} data-state={speech ? 'speech' : 'silence'} />
      <span className='vad-meter__label'>
        {speech ? 'Speech' : 'Silence'} · score {percentage.toString().padStart(2, '0')}%
      </span>
      <p className='sr-only' aria-live='polite'>
        Speech score {percentage}%
      </p>
    </div>
  );
};

const SegmentList = ({
  segments,
  onToggle,
  playingId,
}: {
  segments: readonly Segment[];
  onToggle: (s: Segment) => void;
  playingId: string | null;
}) => {
  if (segments.length === 0) {
    return <p className='placeholder'>Talk into the microphone to capture segments.</p>;
  }

  return (
    <ol className='segment-list'>
      {segments.map((segment) => (
        <li key={segment.id} className='segment-list__item'>
          <button
            type='button'
            className='play-button'
            title={playingId === segment.id ? 'Stop segment' : 'Play segment'}
            onClick={() => onToggle(segment)}
            aria-pressed={playingId === segment.id}
          >
            {playingId === segment.id ? '■' : '▶'}
          </button>
          <span className='segment-list__title'>#{segment.id.slice(0, 6).toUpperCase()}</span>
          <span>start {formatTimestamp(segment.startMs)}</span>
          <span>end {formatTimestamp(segment.endMs)}</span>
          <span>duration {formatDuration(segment.durationMs)}</span>
        </li>
      ))}
    </ol>
  );
};

export const App = () => {
  const {
    devices,
    selectedDeviceId,
    setSelectedDeviceId,
    enumerating,
    error: enumerationError,
    refresh: enumerateAudioInputs,
  } = useAudioInputs({ promptOnMount: true, autoSelectFirst: true, rememberLast: true });

  // Persisted UI state (localStorage): energy threshold, smoothing, capture mode
  const THRESHOLD_KEY = 'saraudio:demo:thresholdDb';
  const SMOOTH_KEY = 'saraudio:demo:smoothMs';
  const MODE_KEY = 'saraudio:demo:captureMode';
  const FALLBACK_KEY = 'saraudio:demo:allowFallback';

  const [thresholdDb, setThresholdDb] = useState(() => {
    if (typeof window === 'undefined') return -55;
    try {
      const raw = window.localStorage.getItem(THRESHOLD_KEY);
      const n = raw !== null ? Number(raw) : NaN;
      return Number.isFinite(n) ? n : -55;
    } catch {
      return -55;
    }
  });
  const [smoothMs, setSmoothMs] = useState(() => {
    if (typeof window === 'undefined') return 30;
    try {
      const raw = window.localStorage.getItem(SMOOTH_KEY);
      const n = raw !== null ? Number(raw) : NaN;
      return Number.isFinite(n) ? n : 30;
    } catch {
      return 30;
    }
  });
  const [hasVadEvent, setHasVadEvent] = useState(false);
  const [mode, setMode] = useState<RuntimeMode>(() => {
    if (typeof window === 'undefined') return 'auto';
    try {
      const raw = window.localStorage.getItem(MODE_KEY);
      if (raw === 'worklet' || raw === 'media-recorder' || raw === 'auto') return raw;
      return 'auto';
    } catch {
      return 'auto';
    }
  });
  const [allowFallback, setAllowFallback] = useState<boolean>(() => {
    if (typeof window === 'undefined') return true;
    try {
      const raw = window.localStorage.getItem(FALLBACK_KEY);
      if (raw === '0') return false;
      return true;
    } catch {
      return true;
    }
  });

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(THRESHOLD_KEY, String(thresholdDb));
    } catch {}
  }, [thresholdDb]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(SMOOTH_KEY, String(smoothMs));
    } catch {}
  }, [smoothMs]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(MODE_KEY, mode);
    } catch {}
  }, [mode]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(FALLBACK_KEY, allowFallback ? '1' : '0');
    } catch {}
  }, [allowFallback]);

  // device enumeration handled by hook

  const audioConstraints = buildAudioConstraints({ deviceId: selectedDeviceId, sampleRate: 16000, channelCount: 1 });

  const segmenterOptions = useMemo(() => ({ preRollMs: 250, hangoverMs: 400 }), []);

  const {
    status,
    error,
    start,
    stop,
    vad: vadState,
    levels,
    segments,
    clearSegments,
    recordings,
  } = useRecorder({
    stages: [vadEnergy({ thresholdDb, smoothMs }), meter()],
    segmenter: segmenterOptions,
    constraints: audioConstraints,
    mode,
    allowFallback,
  });

  const [cleanedUrl, setCleanedUrl] = useState<string | null>(null);
  const [fullUrl, setFullUrl] = useState<string | null>(null);
  const [maskedUrl, setMaskedUrl] = useState<string | null>(null);
  // Web Audio playback state for individual segments
  const audioCtxRef = useRef<AudioContext | null>(null);
  const sourceRef = useRef<AudioBufferSourceNode | null>(null);
  const [playingId, setPlayingId] = useState<string | null>(null);

  const lastVad = vadState ? { speech: vadState.isSpeech, score: vadState.score } : null;
  const isSpeech = vadState?.isSpeech ?? false;
  const rms = levels?.rms ?? 0;
  const db = levels?.db ?? -Infinity;

  useEffect(() => {
    if (lastVad) {
      setHasVadEvent(true);
    }
  }, [lastVad]);

  const isRunning = status === 'running' || status === 'acquiring';
  const meterPercent = Math.min(100, Math.round(rms * 100));
  const levelDb = db === -Infinity ? '-∞' : db.toFixed(1);
  const vadLabel = useMemo(() => {
    if (hasVadEvent) {
      return lastVad?.speech ? 'Speech detected' : 'Silence';
    }
    if (status === 'running') {
      return 'Listening… waiting for speech';
    }
    return 'Silence';
  }, [hasVadEvent, lastVad?.speech, status]);

  const previousStatusRef = useRef(status);
  useEffect(() => {
    if (status === 'running' && previousStatusRef.current !== 'running') {
      setHasVadEvent(false);
    }
    previousStatusRef.current = status;
  }, [status]);

  const handleStartStop = useCallback(() => {
    if (isRunning) {
      void (async () => {
        await stop();
        const cleaned = await recordings.cleaned.getBlob();
        const full = await recordings.full.getBlob();
        const masked = await recordings.masked.getBlob();
        setCleanedUrl(cleaned ? URL.createObjectURL(cleaned) : null);
        setFullUrl(full ? URL.createObjectURL(full) : null);
        setMaskedUrl(masked ? URL.createObjectURL(masked) : null);
        // We no longer show the meta label near Cleaned player.
      })();
      return;
    }
    void start();
  }, [isRunning, start, stop, recordings]);

  const stopCurrent = (): void => {
    const node = sourceRef.current;
    if (node) {
      try {
        node.stop();
      } catch {}
      node.disconnect();
      sourceRef.current = null;
    }
    setPlayingId(null);
  };

  const playSegment = (s: Segment): void => {
    if (!s.pcm || s.pcm.length === 0) return;
    stopCurrent();
    const ctx = audioCtxRef.current ?? new AudioContext({ sampleRate: s.sampleRate });
    audioCtxRef.current = ctx;
    const buffer = segmentToAudioBuffer(ctx, s);
    if (!buffer) return;
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.connect(ctx.destination);
    source.onended = () => {
      if (sourceRef.current === source) sourceRef.current = null;
      setPlayingId((prev) => (prev === s.id ? null : prev));
    };
    sourceRef.current = source;
    setPlayingId(s.id);
    source.start();
  };

  const handleToggleSegment = (s: Segment): void => {
    if (playingId === s.id) {
      stopCurrent();
    } else {
      playSegment(s);
    }
  };

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      stopCurrent();
      const ctx = audioCtxRef.current;
      audioCtxRef.current = null;
      void ctx?.close();
    };
  }, []);

  return (
    <div className='app'>
      <header>
        <h1>SARAUDIO · React Microphone Demo</h1>
        <p>
          This demo uses <code>@saraudio/react</code> hooks on top of the browser runtime. Press&nbsp;
          <strong>Start</strong> to capture the microphone and visualise voice activity.
        </p>
      </header>

      <section className='controls'>
        <div className='controls__device-row'>
          <label className='controls__device'>
            <span>Input device</span>
            <div className='device-select'>
              <select
                value={selectedDeviceId}
                onChange={(event) => setSelectedDeviceId(event.target.value)}
                disabled={enumerating || status === 'running' || status === 'acquiring'}
              >
                {devices.map((device) => (
                  <option key={device.deviceId || `device-${device.label}`} value={device.deviceId}>
                    {device.label || `Microphone ${device.deviceId.slice(0, 6)}`}
                  </option>
                ))}
              </select>
              <button
                type='button'
                onClick={() => void enumerateAudioInputs()}
                disabled={enumerating || status === 'running' || status === 'acquiring'}
                className='refresh-button'
                title='Refresh devices'
              >
                Refresh
              </button>
            </div>
          </label>
          <div className='threshold-controls'>
            <label>
              <span>Energy threshold (dB)</span>
              <input
                type='range'
                min='-90'
                max='-5'
                step='1'
                value={thresholdDb}
                onChange={(event) => setThresholdDb(Number(event.target.value))}
              />
              <span className='threshold-value'>{thresholdDb} dB</span>
            </label>
            <label>
              <span>Smoothing (ms)</span>
              <input
                type='range'
                min='5'
                max='200'
                step='5'
                value={smoothMs}
                onChange={(event) => setSmoothMs(Number(event.target.value))}
              />
              <span className='threshold-value'>{smoothMs} ms</span>
            </label>
          </div>
        </div>
        <div className='controls__device-row' style={{ marginTop: 8 }}>
          <div className='mode-row'>
            <label className='controls__device'>
              <span>Capture mode</span>
              <div className='device-select'>
                <select
                  value={mode}
                  onChange={(e) => setMode(e.target.value as RuntimeMode)}
                  disabled={status === 'running' || status === 'acquiring'}
                >
                  <option value='auto'>auto</option>
                  <option value='worklet'>worklet</option>
                  <option value='media-recorder'>media-recorder</option>
                </select>
              </div>
            </label>
            <label className='controls__device' style={{ minWidth: 140 }}>
              <span>Allow fallback</span>
              <input
                type='checkbox'
                checked={allowFallback}
                onChange={(e) => setAllowFallback(e.target.checked)}
                disabled={status === 'running' || status === 'acquiring'}
                aria-label='Allow automatic fallback when requested mode is unavailable'
              />
            </label>
          </div>
        </div>
        <div className='controls__buttons'>
          <button type='button' onClick={handleStartStop} disabled={status === 'stopping'}>
            {isRunning ? 'Stop' : 'Start'} microphone
          </button>
          <button type='button' onClick={() => clearSegments()} disabled={segments.length === 0}>
            Clear segments
          </button>
        </div>
        <div className='controls__status'>
          {enumerating ? <span className='status status--info'>Scanning devices…</span> : null}
          {devices.length === 0 && !enumerating ? (
            <span className='status status--warning'>No audio inputs found</span>
          ) : null}
          <span className={`status status--${status}`}>Status: {status}</span>
        </div>
        {enumerationError ? <p className='status status--error'>Device error: {enumerationError}</p> : null}
        {error ? <p className='status status--error'>Error: {error.message}</p> : null}
      </section>

      <section className='vad'>
        <h2>Voice Activity</h2>
        <div className='volume-meter' aria-hidden='true'>
          <div className='volume-meter__bar' style={{ width: `${meterPercent}%` }} />
        </div>
        <p className='volume-meter__label'>
          Input level {meterPercent}% ({levelDb} dBFS)
        </p>
        {lastVad ? (
          <VADMeter score={lastVad.score} speech={lastVad.speech} />
        ) : (
          <p className='placeholder'>Meter will update once audio chunks arrive. Adjust threshold if needed.</p>
        )}
        <p className='badge' data-state={hasVadEvent && isSpeech ? 'speech' : 'silence'}>
          {vadLabel}
        </p>
      </section>

      <section className='segments'>
        <h2>Captured Segments (last {segments.length})</h2>
        <SegmentList segments={segments} onToggle={handleToggleSegment} playingId={playingId} />
      </section>

      <section className='segments'>
        <h2>Recordings</h2>
        <div className='segment-list'>
          <div className='segment-list__item'>
            <span className='segment-list__title'>Cleaned (speech only)</span>
            {/* biome-ignore lint/a11y/useMediaCaption: demo player without captions */}
            {cleanedUrl ? <audio controls src={cleanedUrl} /> : <span className='placeholder'>No cleaned yet</span>}
          </div>
          <div className='segment-list__item'>
            <span className='segment-list__title'>Full (entire session)</span>
            {/* biome-ignore lint/a11y/useMediaCaption: demo player without captions */}
            {fullUrl ? <audio controls src={fullUrl} /> : <span className='placeholder'>No full yet</span>}
          </div>
          <div className='segment-list__item'>
            <span className='segment-list__title'>Masked (silence as zeros)</span>
            {/* biome-ignore lint/a11y/useMediaCaption: demo player without captions */}
            {maskedUrl ? <audio controls src={maskedUrl} /> : <span className='placeholder'>No masked yet</span>}
          </div>
        </div>
      </section>

      <footer>
        <p>
          Microphone capture requires HTTPS (or localhost) and user permission. Adjust thresholds inside the demo to
          tune sensitivity for noisy environments.
        </p>
      </footer>
    </div>
  );
};

// examples/nuxt-audio-recorder/app/app.vue
<script setup lang="ts">
import type { Segment } from '@saraudio/core';
import { meter } from '@saraudio/meter';
import { buildAudioConstraints, segmentToAudioBuffer, type RuntimeMode } from '@saraudio/runtime-browser';
import { useAudioInputs, useMeter, useRecorder } from '@saraudio/vue';
import { vadEnergy } from '@saraudio/vad-energy';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';

const THRESHOLD_KEY = 'saraudio:demo:thresholdDb';
const SMOOTH_KEY = 'saraudio:demo:smoothMs';
const MODE_KEY = 'saraudio:demo:captureMode';
const FALLBACK_KEY = 'saraudio:demo:allowFallback';

const thresholdDb = ref(-55);
const smoothMs = ref(30);
const mode = ref<RuntimeMode>('auto');
const allowFallback = ref(true);

onMounted(() => {
  if (typeof window === 'undefined') return;
  try {
    const savedThreshold = window.localStorage.getItem(THRESHOLD_KEY);
    if (savedThreshold) thresholdDb.value = Number(savedThreshold);
    const savedSmooth = window.localStorage.getItem(SMOOTH_KEY);
    if (savedSmooth) smoothMs.value = Number(savedSmooth);
    const savedMode = window.localStorage.getItem(MODE_KEY);
    if (savedMode === 'worklet' || savedMode === 'media-recorder' || savedMode === 'auto') {
      mode.value = savedMode;
    }
    const savedFallback = window.localStorage.getItem(FALLBACK_KEY);
    if (savedFallback) allowFallback.value = savedFallback !== '0';
  } catch {}
});

// Save to localStorage
watch(thresholdDb, (val) => {
  if (typeof window !== 'undefined') {
    try {
      window.localStorage.setItem(THRESHOLD_KEY, String(val));
    } catch {}
  }
});
watch(smoothMs, (val) => {
  if (typeof window !== 'undefined') {
    try {
      window.localStorage.setItem(SMOOTH_KEY, String(val));
    } catch {}
  }
});
watch(mode, (val) => {
  if (typeof window !== 'undefined') {
    try {
      window.localStorage.setItem(MODE_KEY, val);
    } catch {}
  }
});
watch(allowFallback, (val) => {
  if (typeof window !== 'undefined') {
    try {
      window.localStorage.setItem(FALLBACK_KEY, val ? '1' : '0');
    } catch {}
  }
});

// Audio device selection
const audioInputs = useAudioInputs({
  promptOnMount: true,
  autoSelectFirst: true,
  rememberLast: true,
});

// Build audio constraints
const audioConstraints = computed(() =>
  buildAudioConstraints({
  deviceId: audioInputs.selectedDeviceId.value,
  sampleRate: 16000,
  channelCount: 1,
}),
);

// Recorder with dynamic configuration
const rec = useRecorder({
  stages: computed(() => [
  vadEnergy({ thresholdDb: thresholdDb.value, smoothMs: smoothMs.value }),
  meter(),
]),
  segmenter: computed(() => ({ preRollMs: 300, hangoverMs: 500 })),
  constraints: audioConstraints,
  mode,
  allowFallback,
});

const meterLevels = useMeter({ pipeline: rec.pipeline });

// Recordings URLs
const cleanedUrl = ref<string | null>(null);
const fullUrl = ref<string | null>(null);
const maskedUrl = ref<string | null>(null);

// Segment playback
const audioCtxRef = ref<AudioContext | null>(null);
const sourceRef = ref<AudioBufferSourceNode | null>(null);
const playingId = ref<string | null>(null);

const stopCurrent = () => {
  const node = sourceRef.value;
  if (node) {
    try {
      node.stop();
    } catch {}
    node.disconnect();
    sourceRef.value = null;
  }
  playingId.value = null;
};

const playSegment = (s: Segment) => {
  if (!s.pcm || s.pcm.length === 0) return;
  stopCurrent();
  const ctx = audioCtxRef.value ?? new AudioContext({ sampleRate: s.sampleRate });
  audioCtxRef.value = ctx;
  const buffer = segmentToAudioBuffer(ctx, s);
  if (!buffer) return;
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  source.connect(ctx.destination);
  source.onended = () => {
    if (sourceRef.value === source) sourceRef.value = null;
    if (playingId.value === s.id) playingId.value = null;
  };
  sourceRef.value = source;
  playingId.value = s.id;
  source.start();
};

const handleToggleSegment = (s: Segment) => {
  if (playingId.value === s.id) {
    stopCurrent();
  } else {
    playSegment(s);
  }
};

async function handleStart() {
  await rec.start();
}

async function handleStop() {
  await rec.stop();
  meterLevels.reset();

  const cleaned = await rec.recordings.value.cleaned.getBlob();
  const full = await rec.recordings.value.full.getBlob();
  const masked = await rec.recordings.value.masked.getBlob();

  cleanedUrl.value = cleaned ? URL.createObjectURL(cleaned) : null;
  fullUrl.value = full ? URL.createObjectURL(full) : null;
  maskedUrl.value = masked ? URL.createObjectURL(masked) : null;
}

onUnmounted(() => {
  stopCurrent();
  const ctx = audioCtxRef.value;
  audioCtxRef.value = null;
  void ctx?.close();
});

const isRunning = computed(() => rec.status.value === 'running' || rec.status.value === 'acquiring');
</script>

<template>
  <div class='min-h-screen bg-gray-900 text-white p-8'>
    <div class='max-w-6xl mx-auto'>
      <header class='mb-8'>
        <h1 class='text-4xl font-bold mb-4'>SARAUDIO · Nuxt Demo</h1>
        <p class='text-gray-400'>
          Full-featured audio recorder with VAD, device selection, and multiple export formats
        </p>
      </header>

      <!-- Device & Configuration -->
      <section class='mb-8 p-6 bg-gray-800 rounded-lg space-y-4'>
        <h2 class='text-xl font-semibold mb-4'>Configuration</h2>

        <!-- Device Selection -->
        <div class='flex gap-4 items-end'>
          <div class='flex-1'>
            <label class='block text-sm text-gray-400 mb-2'>Input Device</label>
            <select
              v-model='audioInputs.selectedDeviceId.value'
              :disabled='audioInputs.enumerating.value || isRunning'
              class='w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 disabled:opacity-50'
            >
              <option
                v-for='device in audioInputs.devices.value'
                :key='device.deviceId'
                :value='device.deviceId'
              >
                {{ device.label || `Microphone ${device.deviceId.slice(0, 6)}` }}
              </option>
            </select>
          </div>
          <button
            type='button'
            @click='audioInputs.refresh'
            :disabled='audioInputs.enumerating.value || isRunning'
            class='px-4 py-2 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg transition'
          >
            {{ audioInputs.enumerating.value ? 'Scanning...' : 'Refresh' }}
          </button>
        </div>

        <!-- VAD Configuration -->
        <div class='grid grid-cols-2 gap-4'>
          <div>
            <label class='block text-sm text-gray-400 mb-2'>
              Energy Threshold: {{ thresholdDb }} dB
            </label>
            <input
              type='range'
              min='-90'
              max='-5'
              step='1'
              v-model.number='thresholdDb'
              class='w-full'
            />
          </div>
          <div>
            <label class='block text-sm text-gray-400 mb-2'>Smoothing: {{ smoothMs }} ms</label>
            <input type='range' min='5' max='200' step='5' v-model.number='smoothMs' class='w-full' />
          </div>
        </div>

        <!-- Capture Mode -->
        <div class='grid grid-cols-2 gap-4'>
          <div>
            <label class='block text-sm text-gray-400 mb-2'>Capture Mode</label>
            <select
              v-model='mode'
              :disabled='isRunning'
              class='w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 disabled:opacity-50'
            >
              <option value='auto'>Auto</option>
              <option value='worklet'>Worklet</option>
              <option value='media-recorder'>Media Recorder</option>
            </select>
          </div>
          <div class='flex items-end'>
            <label class='flex items-center gap-2 cursor-pointer'>
              <input type='checkbox' v-model='allowFallback' :disabled='isRunning' class='w-4 h-4' />
              <span class='text-sm text-gray-400'>Allow fallback</span>
            </label>
          </div>
        </div>
      </section>

      <!-- Controls -->
      <div class='flex gap-4 mb-8'>
        <button
          type='button'
          @click='handleStart'
          :disabled='isRunning || rec.status.value === "stopping"'
          class='px-6 py-3 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition'
        >
          {{ rec.status.value === 'acquiring' ? 'Acquiring...' : 'Start Microphone' }}
        </button>
        <button
          type='button'
          @click='handleStop'
          :disabled='!isRunning'
          class='px-6 py-3 bg-red-600 hover:bg-red-700 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition'
        >
          Stop Microphone
        </button>
        <button
          type='button'
          @click='rec.clearSegments'
          :disabled='rec.segments.value.length === 0'
          class='px-6 py-3 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition'
        >
          Clear Segments
        </button>
      </div>

      <!-- Status & Errors -->
      <div class='mb-8 space-y-2'>
        <div
          class='px-4 py-2 rounded-lg'
          :class='{
            "bg-green-900/50 border border-green-500": rec.status.value === "running",
            "bg-blue-900/50 border border-blue-500": rec.status.value === "acquiring",
            "bg-gray-800 border border-gray-600": rec.status.value === "idle",
          }'
        >
          <span class='text-sm text-gray-400'>Status:</span>
          <span class='ml-2 font-mono'>{{ rec.status.value }}</span>
        </div>
        <div
          v-if='audioInputs.error.value'
          class='px-4 py-2 bg-red-900/50 border border-red-500 rounded-lg'
        >
          <span class='text-sm text-red-400'>Device Error:</span>
          <span class='ml-2'>{{ audioInputs.error.value }}</span>
        </div>
        <div
          v-if='rec.error.value'
          class='px-4 py-2 bg-red-900/50 border border-red-500 rounded-lg'
        >
          <span class='text-sm text-red-400'>Error:</span>
          <span class='ml-2'>{{ rec.error.value.message }}</span>
        </div>
      </div>

      <!-- VAD & Meter -->
      <div class='grid grid-cols-2 gap-8 mb-8'>
        <!-- VAD -->
        <div class='p-6 bg-gray-800 rounded-lg'>
          <h2 class='text-xl font-semibold mb-4'>Voice Activity</h2>
          <div class='flex items-center gap-4 mb-4'>
            <div
              :class="[
                'w-6 h-6 rounded-full transition-all',
                rec.vad.value?.speech ? 'bg-green-500' : 'bg-gray-600',
              ]"
            />
            <div class='font-mono text-lg'>
              {{ rec.vad.value?.speech ? 'Speech' : 'Silence' }}
            </div>
          </div>
          <div class='text-sm text-gray-400'>
            Score: {{ rec.vad.value?.score.toFixed(2) ?? '0.00' }}
          </div>
        </div>

        <!-- Meter -->
        <div class='p-6 bg-gray-800 rounded-lg'>
          <h2 class='text-xl font-semibold mb-4'>Audio Levels</h2>
          <div class='space-y-3'>
            <div>
              <div class='flex justify-between text-sm text-gray-400 mb-1'>
                <span>RMS</span>
                <span>{{ meterLevels.rms.value.toFixed(3) }}</span>
              </div>
              <div class='w-full bg-gray-700 h-3 rounded overflow-hidden'>
                <div
                  class='bg-blue-500 h-full transition-all'
                  :style='`width: ${Math.min(meterLevels.rms.value * 100, 100)}%`'
                />
              </div>
            </div>
            <div>
              <div class='flex justify-between text-sm text-gray-400 mb-1'>
                <span>Peak</span>
                <span>{{ meterLevels.peak.value.toFixed(3) }}</span>
              </div>
              <div class='w-full bg-gray-700 h-3 rounded overflow-hidden'>
                <div
                  class='bg-green-500 h-full transition-all'
                  :style='`width: ${Math.min(meterLevels.peak.value * 100, 100)}%`'
                />
              </div>
            </div>
            <div class='flex justify-between text-sm text-gray-400'>
              <span>dB</span>
              <span>{{
                meterLevels.db.value === -Infinity ? '-∞' : meterLevels.db.value.toFixed(1)
              }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Segments -->
      <section class='mb-8 p-6 bg-gray-800 rounded-lg'>
        <h2 class='text-xl font-semibold mb-4'>
          Captured Segments ({{ rec.segments.value.length }})
        </h2>
        <div v-if='rec.segments.value.length === 0' class='text-gray-500 text-center py-8'>
          Talk into the microphone to capture segments
        </div>
        <div v-else class='space-y-2 max-h-96 overflow-y-auto'>
          <div
            v-for='segment in rec.segments.value'
            :key='segment.id'
            class='p-4 bg-gray-700 rounded-lg flex items-center gap-4'
          >
            <button
              type='button'
              @click='handleToggleSegment(segment)'
              class='w-10 h-10 flex items-center justify-center bg-gray-600 hover:bg-gray-500 rounded-lg transition'
              :title='playingId === segment.id ? "Stop segment" : "Play segment"'
            >
              {{ playingId === segment.id ? '■' : '▶' }}
            </button>
            <div class='flex-1'>
              <div class='flex items-center justify-between mb-1'>
                <div class='font-mono text-xs text-gray-400'>
                  #{{ segment.id.slice(0, 8).toUpperCase() }}
                </div>
                <div class='text-xs text-gray-400'>
                  {{ (segment.durationMs / 1000).toFixed(2) }}s
                </div>
              </div>
              <div class='text-sm text-gray-300'>
                {{ new Date(segment.startMs).toLocaleTimeString() }} →
                {{ new Date(segment.endMs).toLocaleTimeString() }}
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Recordings -->
      <section class='p-6 bg-gray-800 rounded-lg'>
        <h2 class='text-xl font-semibold mb-4'>Recordings</h2>
        <div class='space-y-4'>
          <div class='p-4 bg-gray-700 rounded-lg'>
            <div class='text-sm font-medium mb-2'>Cleaned (speech only)</div>
            <audio v-if='cleanedUrl' controls :src='cleanedUrl' class='w-full' />
            <div v-else class='text-sm text-gray-500'>No recording yet</div>
          </div>
          <div class='p-4 bg-gray-700 rounded-lg'>
            <div class='text-sm font-medium mb-2'>Full (entire session)</div>
            <audio v-if='fullUrl' controls :src='fullUrl' class='w-full' />
            <div v-else class='text-sm text-gray-500'>No recording yet</div>
          </div>
          <div class='p-4 bg-gray-700 rounded-lg'>
            <div class='text-sm font-medium mb-2'>Masked (silence as zeros)</div>
            <audio v-if='maskedUrl' controls :src='maskedUrl' class='w-full' />
            <div v-else class='text-sm text-gray-500'>No recording yet</div>
          </div>
        </div>
      </section>

      <footer class='mt-8 text-sm text-gray-500 text-center'>
        <p>
          Microphone requires HTTPS (or localhost) and user permission. Adjust thresholds to tune
          sensitivity.
        </p>
      </footer>
    </div>
  </div>
</template>
